name: run
on:
  schedule:
    - cron:  '0 6 * * *' # tous les jours à 6h
    - cron: '28 10 10 11 *' # 10 nov. à 11h28 heure de Paris
jobs:
  download-data-and-audit-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone to Europe/Paris
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Paris
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies from Pipfile
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy
      - name: Run the CLI command to download consolidated data
        run: |
          pipenv run python . download
      - name: Run the quality audit on last 100k rows
        run: |
          pipenv run python . audit --rows 100000
      - name: Upload audit results as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: audit-100000lignes.json
          path: ./data/audit-100000lignes.json
          retention-days: 7
      - name: Upload audit details per line as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: details-100000lignes.json
          path: ./data/details-100000lignes.json
          retention-days: 7
      - name: Upload source data as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: decp.json
          path: ./data/decp.json
          retention-days: 7